### ISSUE TITLE
install error: dbus module not found

### ISSUE THREAD

**Issue by NuVanDibe** [ryanrudolfoba/SteamOS-Waydroid-Installer#137]
```
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.5.0-valve12-1-neptune-65-g1889664e19fc is supported. Proceed to next step.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
Casualsnek repo has been successfully cloned!
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-11-09
pacman keyring has been initialized!
binder kernel module not found! Installing binder!
binder kernel module has been installed!
waydroid and cage has been installed!
Config file missing. Lets configure waydroid.
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
Waydroid did not initialize correctly
Most probably this is due to python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python /home/deck/miniconda3/bin/python
Output of which python - /home/deck/miniconda3/bin/python
Output of python version - Python 3.12.3
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

```

SteamOS preview build

**Comment by ryanrudolfoba** [comment]
you have another python installed that is interfering -
![image](https://github.com/user-attachments/assets/7035c86b-84fa-4252-96b5-497c87be0e9d)

i dont use that. most probably you have another application that automatically installed a different pyton.

**Comment by NuVanDibe** [comment]
Thanks; removing the miniconda PATH section in .bashrc alone was sufficient to resolve.
