### ISSUE TITLE
Waydroid Android TV builds

### ISSUE THREAD

**Issue by havy1601** [ryanrudolfoba/SteamOS-Waydroid-Installer#151]
Would it be possible to use the Waydroid Android TV custom image on the steamdeck with your script?
It would be great for a seamless experience when docked and connected to a TV.

For example:
https://github.com/supechicken/waydroid-androidtv-build

**Comment by havy1601** [comment]
Ok, I got it running now. SupeChicken666 the creator of the android tv build told me the following:
"You need to wipe the data directory of Waydroid first (rm -r ~/.local/share/waydroid) after replacing the stock one with the new system image."

**Comment by ryanrudolfoba** [comment]
I can add that option in the Waydroid Toolbox. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by slynobody** [comment]
highly second integrating this (beside GAPPS or NONE).
working really good here.

only thing is getting widevine-driven-apps like disney, netflix, mubi to run. so at least the typical widevine-script should be triggered when ATV is chosen? Or is there another widevine-script for the other levels this image should open as possibility?

**Comment by ryanrudolfoba** [comment]
trying to build but getting stuck on vendor.img - https://github.com/supechicken/waydroid-androidtv-build/issues/16

if im not able to figure it out i'll just use prebuilt one's from supechicken666

**Comment by ryanrudolfoba** [comment]
build completed and it boots!

![image](https://github.com/user-attachments/assets/f6de9d00-ccf8-4561-aadc-3d1c87679a85)

**Comment by Gizzy98** [comment]
> build completed and it boots!
> 
> ![image](https://private-user-images.githubusercontent.com/98122529/394868324-f6de9d00-ccf8-4561-aadc-3d1c87679a85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTMyMTIsIm5iZiI6MTczNDAxMjkxMiwicGF0aCI6Ii85ODEyMjUyOS8zOTQ4NjgzMjQtZjZkZTlkMDAtY2NmOC00NTYxLWFhZGMtM2QxYzg3Njc5YTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE0MTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NzdiNmJlYjI1ZjMzNDkxNGQ3MGNkNTBkZDMxMzg1NGZiZjM3YzQ2ZWZhNTc4N2U2ZTgzMDNlNjA3ZDJhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oo5nrpRyilGbUZE-fyJGc2KNmh2hxgGQpsXkJBhj8Vo)

Hi, 

Running the script today and the KONSOLE just says 'Selected Android TV'
Then it just returns to the deck directory with a prompt and doesn't appear to actually install anything. 

Any ideas what I'm doing wrong? 

Thanks

**Comment by ryanrudolfoba** [comment]
Still not available. That's just my placeholder for things to come. Sorry i thought its just on my personal testing didn't realize i uploaded it.

**Comment by Gizzy98** [comment]
> Still not available. That's just my placeholder for things to come. Sorry i thought its just on my personal testing didn't realize i uploaded it.
> 
> EDIT: so that one got uploaded Dec06 about a week ago. I'll edit it to remove the placeholder

Ah right, cool. No problem mate 👍🏻 Thank you.

**Comment by heyboots** [comment]
Literally looking for exactly this today, can't wait to try it out once its ready. Was also thrown off by the placeholder TV option in the installer until I checked issues.

**Comment by Cal648-92** [comment]
Those that have got this working, do you have larger than default partitions? 

I don't seem to have space for everything. I've tried to work around it with symlinks pointing to an offload folder in my home partition but when I initialize (sudo waydroid init -f) it fails to restarts the container. The log seems to suggest it's failing to mount stuff. I've no idea what to make of any of it. The stuff that's failing doesn't seem to be anything to do with the symlinks. It looks Wayland related.

(006836) [03:27:22] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:27:22] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: ../src/lxc/conf.c: turn_into_dependent_mounts: 3948 No such file or directory - Failed to recursively turn old root mount tree into dependent mount. Continuing...
RUNNING
(006836) [03:27:22] waiting 10 seconds for container to start...
(007070) [03:27:23] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(006890) [03:27:23] Skipping clipboard manager service because of missing pyclip package
(007294) [03:27:24] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(007373) [03:27:25] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(007455) [03:27:27] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(007955) [03:27:28] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(007968) [03:27:29] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(007981) [03:27:30] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(007998) [03:27:32] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(006890) [03:27:32] waydroidusermonitor: Received transaction: 1
(006890) [03:27:32] Android with user 0 is ready
(008345) [03:27:33] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(008355) [03:27:33] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(008459) [03:27:33] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(008646) [03:27:34] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(008647) [03:27:34] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(006836) [03:27:41] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(006836) [03:29:36] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(009560) [03:29:46] Save config: /var/lib/waydroid/waydroid.cfg
(009560) [03:29:46] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(009560) [03:29:46] Stopping container
(006836) [03:29:46] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(006836) [03:29:46] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(006836) [03:29:46] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(006836) [03:29:46] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:46] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(006836) [03:29:47] % systemctl is-enabled -q nfcd
(006836) [03:29:47] % umount /home/deck/offload/waydroid/rootfs/vendor/waydroid.prop
(006836) [03:29:47] % umount /home/deck/offload/waydroid/rootfs/vendor
(006836) [03:29:47] % umount /home/deck/offload/waydroid/rootfs
(009560) [03:29:47] % modprobe -q ashmem_linux
(009560) [03:29:47] % lxc-info --version
5.0.3
(009560) [03:29:47] % mkdir -p /var/lib/waydroid/lxc/waydroid
(009560) [03:29:47] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(009560) [03:29:47] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(009560) [03:29:47] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(009560) [03:29:47] % systemctl is-active -q apparmor
(009560) [03:29:47] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(009560) [03:29:47] Starting container
(006836) [03:29:47] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(006836) [03:29:47] % systemctl is-active -q nfcd
(006836) [03:29:47] % chmod 777 -R /dev/dri
(006836) [03:29:47] % chmod 777 -R /dev/fb0
(006836) [03:29:47] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(006836) [03:29:47] % mount -o ro /etc/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(006836) [03:29:47] % mount -o ro /etc/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(006836) [03:29:47] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(006836) [03:29:47] Save config: /var/lib/waydroid/waydroid.cfg
(006836) [03:29:47] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(006836) [03:29:47] New background process: pid=9699, output=background
(006836) [03:29:47] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
**lxc-start: waydroid: ../src/lxc/conf.c: turn_into_dependent_mounts: 3948 No such file or directory - Failed to recursively turn old root mount tree into dependent mount. Continuing...
lxc-start: waydroid: ../src/lxc/utils.c: safe_mount: 1220 No such file or directory - Failed to mount "/run/user/1000/wayland-0" onto "/usr/lib/lxc/rootfs/run/xdg/wayland-0"
lxc-start: waydroid: ../src/lxc/conf.c: mount_entry: 2439 No such file or directory - Failed to mount "/run/user/1000/wayland-0" on "/usr/lib/lxc/rootfs/run/xdg/wayland-0"
lxc-start: waydroid: ../src/lxc/conf.c: lxc_setup: 4412 Failed to setup mount entries
lxc-start: waydroid: ../src/lxc/start.c: do_start: 1272 Failed to setup container "waydroid"
lxc-start: waydroid: ../src/lxc/sync.c: sync_wait: 34 An error occurred in another process (expected sequence number 3)
lxc-start: waydroid: ../src/lxc/start.c: __lxc_start: 2107 Failed to spawn container "waydroid"**
STOPPED
(006836) [03:29:47] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:47] waiting 10 seconds for container to start...
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
(006836) [03:29:48] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:48] waiting 9 seconds for container to start...
(006836) [03:29:49] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:49] waiting 8 seconds for container to start...
(006836) [03:29:50] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:50] waiting 7 seconds for container to start...
(006836) [03:29:51] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:51] waiting 6 seconds for container to start...
(006836) [03:29:52] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:52] waiting 5 seconds for container to start...
(006836) [03:29:53] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:53] waiting 4 seconds for container to start...
(006836) [03:29:54] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:54] waiting 3 seconds for container to start...
(006836) [03:29:55] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:55] waiting 2 seconds for container to start...
(006836) [03:29:56] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(006836) [03:29:56] waiting 1 seconds for container to start...
(009560) [03:29:57] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
    helpers.lxc.start(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 400, in start
    wait_for_running(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 394, in wait_for_running
    raise OSError("container failed to start")
OSError: container failed to start

(009560) [03:29:57] Failed to restart container. Please do so manually.

**Comment by ryanrudolfoba** [comment]
Script has been updated now so the TV option works - it installs a custom build of Android 11 TV image (that has been uploaded for several weeks now in the RELEASES section). 

If you want to test - completely uninstall waydroid using Waydroid Toolbox in Desktop Mode, then clone the repo again to get the latest version. Select TV11 as the option to install.

NOTE: there is no Playstore / Google Services on this as the `var` partition is tiny it wont fit. ARM translation layer is not possible too due to the contraints on the limited space in the `var` parition.

You will need to sideload APKs to install applications. [Here is a guide how to sideload APKs.](https://youtu.be/LglEbSdRc0M)

[Here is a demo of Android TV on SteamOS.](https://youtu.be/gNFxrojouiM) Take note that is an older video using a custom partitioning scheme to have a larger `var` partition.
