### ISSUE TITLE
Something went wrong! Performing cleanup. 

### ISSUE THREAD

**Issue by wskkysdsy** [ryanrudolfoba/SteamOS-Waydroid-Installer#154]
``Waydroid initialization completed without errors!
[sudo] deck 的密码：INFO: Downloading libndktranslation.zip now to /home/deck/.cache/waydroid-script/downloads/libndktranslation.zip .....
Traceback (most recent call last):
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /supremegamers/vendor_google_proprietary_ndk_translation-prebuilt/archive/9324a8914b649b885dad6f2bfd14a67e5d1520bf.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deck/AUR/waydroid/waydroid_script/main.py", line 358, in <module>
    main()
  File "/home/deck/AUR/waydroid/waydroid_script/main.py", line 351, in main
    args.func(args)
  File "/home/deck/AUR/waydroid/waydroid_script/main.py", line 113, in install_app
    item.install()
  File "/home/deck/AUR/waydroid/waydroid_script/stuff/general.py", line 174, in install
    self.download()
  File "/home/deck/AUR/waydroid/waydroid_script/stuff/general.py", line 47, in download
    loc_md5 = download_file(self.dl_link, self.download_loc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/tools/helper.py", line 94, in download_file
    response = requests.get(url, stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/AUR/waydroid/waydroid_script/venv/lib/python3.11/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /supremegamers/vendor_google_proprietary_ndk_translation-prebuilt/archive/9324a8914b649b885dad6f2bfd14a67e5d1520bf.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))
Error with casualsnek script. Run the script again.

Something went wrong! Performing cleanup. 

Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

**Comment by ryanrudolfoba** [comment]
sorry for late reply. clone the repo again to get the latest version and see if that fixes your issues.

**Comment by ryanrudolfoba** [comment]
if you need further help please feel free to update this issue.

**Comment by wskkysdsy** [comment]
[20:55:09] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20241012-GAPPS-waydroid_x86_64-system.zip/download
[20:58:24] Validating system image
[20:58:24] ERROR: Downloaded system image hash doesn't match, expected: 86318b7d099867f0ee72c982780110372128613c4839678e0c6a0eee306af9ce
[20:58:24] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
Waydroid did not initialize correctly.
This could be a hash mismatch / corrupted download.
This could also be a python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python
Output of which python - /usr/bin/python
Output of python version - Python 3.11.3
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

**Comment by wskkysdsy** [comment]
> if you need further help please feel free to update this issue.

[20:55:09] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20241012-GAPPS-waydroid_x86_64-system.zip/download
[20:58:24] Validating system image
[20:58:24] ERROR: Downloaded system image hash doesn't match, expected: 86318b7d099867f0ee72c982780110372128613c4839678e0c6a0eee306af9ce
[20:58:24] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
Waydroid did not initialize correctly.
This could be a hash mismatch / corrupted download.
This could also be a python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python
Output of which python - /usr/bin/python
Output of python version - Python 3.11.3
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

**Comment by wskkysdsy** [comment]
May I ask what problem has occurred?

**Comment by ryanrudolfoba** [comment]
This is the relevant error -

> [20:58:24] Validating system image
[20:58:24] ERROR: Downloaded system image hash doesn't match, expected: 86318b7d099867f0ee72c982780110372128613c4839678e0c6a0eee306af9ce
[20:58:24] See also: https://github.com/waydroid
Run 'waydroid log' for details.
Waydroid did not initialize correctly.
This could be a hash mismatch / corrupted download.

It means somehow the download is corrupted. Nothing much i can do about that. Just re-run the script and it will redownload it.
