### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Nekomian** [ryanrudolfoba/SteamOS-Waydroid-Installer#187]
Not sure if im doing any of this correctly TBH i have never opend a github issue

Anways while installing im running into an error after selecting if i want gapps or not

`gpg: next trustdb check due at 2024-12-21
pacman keyring has been initialized!
Binder kernel module not found or not up to date! Installing binder!
Binder kernel module has been installed!
waydroid and cage has been installed!
Downloading waydroid image from sourceforge.
This can take a few seconds to a few minutes depending on the internet connection and the speed of the sourceforge mirror.
Sometimes it connects to a slow sourceforge mirror and the downloads are slow -. This is beyond my control!
If the downloads are slow due to a slow sourceforge mirror - cancel the sript (CTL-C) and run it again.
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 7, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
Waydroid did not initialize correctly.
This could be a hash mismatch / corrupted download.
This could also be a python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python /home/deck/miniconda3/bin/python
Output of which python - /home/deck/miniconda3/bin/python
Output of python version - Python 3.7.16
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.
`

Im unsure what could be causing it

**Comment by ryanrudolfoba** [comment]
Based on the error message this is the issue -

![Screenshot_20241121-163711](https://github.com/user-attachments/assets/535105c3-7fa1-4edb-995c-7cde21d1ab42)

It means you have a different python installed on your system.

**Comment by Nekomian** [comment]
That makes sense which would be the correct version go install ? I'm sadly not quite sure where to find that information
