### ISSUE TITLE
Install fails when downloading waydroid image

### ISSUE THREAD

**Issue by Azail07** [ryanrudolfoba/SteamOS-Waydroid-Installer#209]
Downloading waydroid image from sourceforge.
This can take a few seconds to a few minutes depending on the internet connection and the speed of the sourceforge mirror.
Sometimes it connects to a slow sourceforge mirror and the downloads are slow -. This is beyond my control!
If the downloads are slow due to a slow sourceforge mirror - cancel the script (CTL-C) and run it again.
[19:58:41] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20241228-GAPPS-waydroid_x86_64-system.zip/download
[19:58:41] ERROR: <urlopen error [SSL] record layer failure (_ssl.c:1006)>
[19:58:41] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
Waydroid did not initialize correctly.
This could be a hash mismatch / corrupted download.
This could also be a python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python /usr/share/man/man1/python.1.gz
Output of which python - /usr/bin/python
Output of python version - Python 3.11.7
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

**Comment by ryanrudolfoba** [comment]
could be an issue with the sourceforge mirror. try running the install again.

**Comment by Azail07** [comment]
Still the same urlopen error...

**Comment by Snoopy8934** [comment]
I'm also getting the same error, I've uninstalled/re-installed countless times over the last 2 days.

**Comment by HandSomeNissan** [comment]
I am getting the same issue too.

**Comment by HandSomeNissan** [comment]
Seems like im getting a different error though: Downloading waydroid image from sourceforge.
This can take a few seconds to a few minutes depending on the internet connection and the speed of the sourceforge mirror.
Sometimes it connects to a slow sourceforge mirror and the downloads are slow -. This is beyond my control!
If the downloads are slow due to a slow sourceforge mirror - cancel the script (CTL-C) and run it again.
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 7, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
Waydroid did not initialize correctly.
This could be a hash mismatch / corrupted download.
This could also be a python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python
Output of which python - /usr/bin/python
Output of python version - Python 3.11.7
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

**Comment by Snoopy8934** [comment]
> Still the same urlopen error...

Any luck on addressing this issue? I've been trying to re-install multiple times a day the last few days with no luck.

**Comment by ryanrudolfoba** [comment]
script has been working fine for me. I dont get `urlopen SSL` error. Another user also used the script just yesterday and it worked fine -

![Screenshot_20250103-162100](https://github.com/user-attachments/assets/9d6da08b-d7c3-4a78-9412-26c22e344766)


With that said it could be your internet connection is blocking sourceforge website?

Try using phone hotspot to isolate.

**Comment by Snoopy8934** [comment]
Just used the Hotspot. It's working now. Thanks!

**Comment by tlsimmons88** [comment]
I am getting the same error 

SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
SteamOS 3.6.20 - kernel version 6.5.0-valve22-1-neptune-65 is supported. Proceed to next step.
Checking if home partition has enough free space
home partition has 962217988 free space.
home partition has enough free space.
Checking if var partition has enough free space
var partition has 212661 free space.
var partition has enough free space.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
Cloning casualsnek repo.
This can take a few minutes depending on the speed of the internet connection and if github is having issues.
If the git clone is slow - cancel the script (CTL-C) and run it again.
Casualsnek repo has been successfully cloned!
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2025-01-25
pacman keyring has been initialized!
Binder kernel module not found or not up to date! Installing binder!
Binder kernel module has been installed!
waydroid and cage has been installed!
Downloading waydroid image from sourceforge.
This can take a few seconds to a few minutes depending on the internet connection and the speed of the sourceforge mirror.
Sometimes it connects to a slow sourceforge mirror and the downloads are slow -. This is beyond my control!
If the downloads are slow due to a slow sourceforge mirror - cancel the script (CTL-C) and run it again.
[07:42:39] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20250104-GAPPS-waydroid_x86_64-system.zip/download
[07:42:39] ERROR: <urlopen error [SSL] record layer failure (_ssl.c:1006)>
[07:42:39] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
Waydroid did not initialize correctly.
This could be a hash mismatch / corrupted download.
This could also be a python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python
Output of which python - /usr/bin/python
Output of python version - Python 3.11.7
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

**Comment by ryanrudolfoba** [comment]
> I am getting the same error
> 
> SteamOS Waydroid Installer Script by ryanrudolf https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer YT - 10MinuteSteamDeckGamer Script is running in Desktop Mode. Checking if kernel is supported. SteamOS 3.6.20 - kernel version 6.5.0-valve22-1-neptune-65 is supported. Proceed to next step. Checking if home partition has enough free space home partition has 962217988 free space. home partition has enough free space. Checking if var partition has enough free space var partition has 212661 free space. var partition has enough free space. Please enter current sudo password: Checking if the sudo password is correct. Sudo password is good! Cloning casualsnek repo. This can take a few minutes depending on the speed of the internet connection and if github is having issues. If the git clone is slow - cancel the script (CTL-C) and run it again. Casualsnek repo has been successfully cloned! ==> Appending keys from archlinux.gpg... ==> Appending keys from holo.gpg... ==> Updating trust database... gpg: next trustdb check due at 2025-01-25 pacman keyring has been initialized! Binder kernel module not found or not up to date! Installing binder! Binder kernel module has been installed! waydroid and cage has been installed! Downloading waydroid image from sourceforge. This can take a few seconds to a few minutes depending on the internet connection and the speed of the sourceforge mirror. Sometimes it connects to a slow sourceforge mirror and the downloads are slow -. This is beyond my control! If the downloads are slow due to a slow sourceforge mirror - cancel the script (CTL-C) and run it again. [07:42:39] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20250104-GAPPS-waydroid_x86_64-system.zip/download [07:42:39] ERROR: <urlopen error [SSL] record layer failure (_ssl.c:1006)> [07:42:39] See also: https://github.com/waydroid Run 'waydroid log' for details. Waydroid did not initialize correctly. This could be a hash mismatch / corrupted download. This could also be a python issue. Attach this screenshot when filing a bug report! Output of whereis python - python: /usr/bin/python Output of which python - /usr/bin/python Output of python version - Python 3.11.7 Something went wrong! Performing cleanup. Run the script again to install waydroid. Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

Same recommendation - script is running fine. It is your network connection having issues with sourceforge.

**Comment by agilgur5** [comment]
This appears to be upstream in Waydroid: https://github.com/waydroid/waydroid/issues/1662.
It is a network/firewall/proxy issue though, so not specific to Waydroid either. The workaround is to manually download the files it's trying to download for you: https://github.com/waydroid/waydroid/issues/1662#issuecomment-2569045844
