### ISSUE TITLE
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)

### ISSUE THREAD

**Issue by ghost** [ryanrudolfoba/SteamOS-Waydroid-Installer#96]
chmod: mit der ins Leere weisenden symbolischen Verknüpfung '/dev/anbox-binder' kann nicht
gearbeitet werden
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
[15:22:20] Starting waydroid session
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'id.waydro.Session': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 64, in maybeLaunchLater
    tools.helpers.ipc.DBusSessionService()
  File "/usr/lib/waydroid/tools/helpers/ipc.py", line 44, in DBusSessionService
    return dbus.Interface(dbus.SessionBus().get_object("id.waydro.Session", object_path), intf)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name id.waydro.Session was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 30, in emit
    self._args.logfd.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 126, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 132, in showFullUI
    maybeLaunchLater(args, justShow)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 71, in maybeLaunchLater
    logging.error("Starting waydroid session")
  File "/usr/lib/python3.11/logging/__init__.py", line 2115, in error
    root.error(msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 35, in emit
    self.handleError(record)
Message: 'Starting waydroid session'
Arguments: ()
[15:22:20] Introspect error on :1.186:/ContainerManager: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'id.waydro.Session': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 64, in maybeLaunchLater
    tools.helpers.ipc.DBusSessionService()
  File "/usr/lib/waydroid/tools/helpers/ipc.py", line 44, in DBusSessionService
    return dbus.Interface(dbus.SessionBus().get_object("id.waydro.Session", object_path), intf)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name id.waydro.Session was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 30, in emit
    self._args.logfd.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 126, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 132, in showFullUI
    maybeLaunchLater(args, justShow)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 72, in maybeLaunchLater
    tools.actions.session_manager.start(args, launchNow, background=False)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 90, in start
    tools.helpers.ipc.DBusContainerService().Start(session)
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 71, in __call__
    self._block()
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 424, in _introspect_block
    self._pending_introspect.block()
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 592, in msg_reply_handler
    error_handler(DBusException(name=message.get_error_name(),
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 407, in _introspect_error_handler
    _logger.error("Introspect error on %s:%s: %s.%s: %s",
  File "/usr/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 35, in emit
    self.handleError(record)
Message: 'Introspect error on %s:%s: %s.%s: %s'
Arguments: (dbus.String(':1.186'), '/ContainerManager', 'dbus.exceptions', 'DBusException', DBusException(dbus.String('Message recipient disconnected from message bus without replying')))
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'id.waydro.Session': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 64, in maybeLaunchLater
    tools.helpers.ipc.DBusSessionService()
  File "/usr/lib/waydroid/tools/helpers/ipc.py", line 44, in DBusSessionService
    return dbus.Interface(dbus.SessionBus().get_object("id.waydro.Session", object_path), intf)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name id.waydro.Session was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 30, in emit
    self._args.logfd.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 126, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 132, in showFullUI
    maybeLaunchLater(args, justShow)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 72, in maybeLaunchLater
    tools.actions.session_manager.start(args, launchNow, background=False)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 90, in start
    tools.helpers.ipc.DBusContainerService().Start(session)
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 71, in __call__
    self._block()
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 424, in _introspect_block
    self._pending_introspect.block()
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 592, in msg_reply_handler
    error_handler(DBusException(name=message.get_error_name(),
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 413, in _introspect_error_handler
    _logger.debug('Executing introspect queue due to error')
  File "/usr/lib/python3.11/logging/__init__.py", line 1477, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 35, in emit
    self.handleError(record)
Message: 'Executing introspect queue due to error'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'id.waydro.Session': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 64, in maybeLaunchLater
    tools.helpers.ipc.DBusSessionService()
  File "/usr/lib/waydroid/tools/helpers/ipc.py", line 44, in DBusSessionService
    return dbus.Interface(dbus.SessionBus().get_object("id.waydro.Session", object_path), intf)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name id.waydro.Session was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 90, in start
    tools.helpers.ipc.DBusContainerService().Start(session)
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.186 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 30, in emit
    self._args.logfd.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 126, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 132, in showFullUI
    maybeLaunchLater(args, justShow)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 72, in maybeLaunchLater
    tools.actions.session_manager.start(args, launchNow, background=False)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 92, in start
    logging.debug(e)
  File "/usr/lib/python3.11/logging/__init__.py", line 2158, in debug
    root.debug(msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1477, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 35, in emit
    self.handleError(record)
Message: DBusException('The name :1.186 was not provided by any .service files')
Arguments: ()
[15:22:20] WayDroid container is not listening
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'id.waydro.Session': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 64, in maybeLaunchLater
    tools.helpers.ipc.DBusSessionService()
  File "/usr/lib/waydroid/tools/helpers/ipc.py", line 44, in DBusSessionService
    return dbus.Interface(dbus.SessionBus().get_object("id.waydro.Session", object_path), intf)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name id.waydro.Session was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 90, in start
    tools.helpers.ipc.DBusContainerService().Start(session)
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.186 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 30, in emit
    self._args.logfd.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 126, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 132, in showFullUI
    maybeLaunchLater(args, justShow)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 72, in maybeLaunchLater
    tools.actions.session_manager.start(args, launchNow, background=False)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 96, in start
    logging.error("WayDroid container is not listening")
  File "/usr/lib/python3.11/logging/__init__.py", line 2115, in error
    root.error(msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 35, in emit
    self.handleError(record)
Message: 'WayDroid container is not listening'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 30, in emit
    self._args.logfd.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 121, in main
    helpers.lxc.shell(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 432, in shell
    state = status(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 376, in status
    return tools.helpers.run.user(args, command, output_return=True).strip()
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 311, in core
    logging.debug(log_message)
  File "/usr/lib/python3.11/logging/__init__.py", line 2158, in debug
    root.debug(msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1477, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 35, in emit
    self.handleError(record)
Message: '% lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH'
Arguments: ()
[15:22:35] Couldn't get LXC status. Assuming STOPPED.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 376, in status
    return tools.helpers.run.user(args, command, output_return=True).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 335, in core
    (code, output_after_run) = foreground_pipe(args, cmd, working_dir,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 178, in foreground_pipe
    pipe_read(args, process, output_to_stdout, output_return,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 80, in pipe_read
    args.logfd.flush()
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 30, in emit
    self._args.logfd.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 121, in main
    helpers.lxc.shell(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 432, in shell
    state = status(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 378, in status
    logging.info("Couldn't get LXC status. Assuming STOPPED.")
  File "/usr/lib/python3.11/logging/__init__.py", line 2148, in info
    root.info(msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1489, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 35, in emit
    self.handleError(record)
Message: "Couldn't get LXC status. Assuming STOPPED."
Arguments: ()
[15:22:35] WayDroid container is STOPPED
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 30, in emit
    self._args.logfd.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 121, in main
    helpers.lxc.shell(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 436, in shell
    logging.error("WayDroid container is {}".format(state))
  File "/usr/lib/python3.11/logging/__init__.py", line 2115, in error
    root.error(msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 35, in emit
    self.handleError(record)
Message: 'WayDroid container is STOPPED'
Arguments: ()

**Comment by ryanrudolfoba** [comment]
could be a python issue. please try this in konsole -

which python\
whereis python

**Comment by ryanrudolfoba** [comment]
i've updated the script - it might fix the issue you are having.
